version: '3.3'

services:
  psql:
    container_name: zsb-db
    image: postgres:11.4
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${ZSB_USER}
      POSTGRES_PASSWORD: ${ZSB_PASSWORD}
      POSTGRES_DB: ${ZSB_USER}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: zsb-backend
    image: zsb-backend
    restart: always
    ports:
      - 9000:9000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://psql:5432/${ZSB_USER}
      DB_USER: ${ZSB_USER}
      DB_PASSWORD: ${ZSB_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_SENDER: ${MAIL_SENDER}
    depends_on:
      - psql
    volumes:
      - signatures_vol:/app/signatures

  frontend:
    container_name: zsb-frontend
    image: zsb-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_cert_vol:/etc/cert
      - nginx_config_vol:/etc/nginx/conf.d
    build:
      context: ../zsb-frontend
      dockerfile: Dockerfile

volumes:
  psql_vol:
  nginx_cert_vol:
  nginx_config_vol:
  signatures_vol:
