version: '3.3'

services:
  psql:
    container_name: zsb-db
    image: postgres:11.4
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${ZSB_USER}
      POSTGRES_PASSWORD: ${ZSB_PASSWORD}
      POSTGRES_DB: ${ZSB_USER}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: zsb-backend
    image: zsb-backend
    restart: always
    ports:
      - 9000:9000
    environment:
      DB_URL: jdbc:postgresql://psql:5432/${ZSB_USER}
      DB_USER: ${ZSB_USER}
      DB_PASSWORD: ${ZSB_PASSWORD}
    depends_on:
      - psql

volumes:
  psql_vol: